[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "llama-index>=0.14.23",
    "llama-index-embeddings-openai>=0.6.0",
    "llama-index-embeddings-openai-like>=0.3.1",
    "llama-index-vector-stores-qdrant>=0.10.2",
    "mcp[cli]>=1.28.1",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.18.0",
    "watchdog>=6.0.0",
]
