[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.3",
    "beautifulsoup4>=4.15.0",
    "llama-index>=0.14.23",
    "llama-index-embeddings-openai>=0.6.0",
    "llama-index-embeddings-openai-like>=0.3.1",
    "llama-index-readers-file>=0.6.0",
    "llama-index-vector-stores-qdrant>=0.10.2",
    "mcp[cli]>=1.28.1",
    "pypdf>=6.14.2",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "qdrant-client>=1.18.0",
    "requests>=2.34.2",
    "watchdog>=6.0.0",
]

[dependency-groups]
dev = [
    "types-beautifulsoup4>=4.12.0.20250516",
    "types-pyyaml>=6.0.12.20260518",
    "types-requests>=2.33.0.20260712",
]
